version: '3.6'
services:
  redis:
    container_name: db-lab-redis
    image: redis:5.0.5
    command: redis-server --appendonly yes
    hostname: redis
    networks:
      - db-lab
    ports:
      - 6379:6379
  postgres:
    container_name: db-lab-postgres
    image: postgres:13.2
    environment:
      - POSTGRES_DB=db-lab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db-lab
    ports:
      - 5432:5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    container_name: db-lab-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - db-lab
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - mailer-volume:/app/packages/mailer
    ports:
      - 3001:3001
    depends_on:
      - redis
  migrator:
    container_name: db-lab-migrator
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.migrator
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - db-lab
    volumes:
      - ./apps/api/src:/app/apps/api/src
  scheduler:
    container_name: db-lab-scheduler
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.scheduler
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    networks:
      - db-lab
    volumes:
      - ./apps/api/src:/app/apps/api/src
  web:
    container_name: db-lab-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    volumes:
      - ./apps/web/src:/app/apps/web/src
      - ./apps/web/public:/app/apps/web/public
    networks:
      - db-lab
    ports:
      - 3002:3002
  mailer:
    container_name: db-lab-mailer
    build:
      context: .
      dockerfile: ./packages/mailer/Dockerfile
      target: development
      args:
        NODE_ENV: development
        APP_ENV: development
    volumes:
      - mailer-volume:/app/packages/mailer/dist
      - ./packages/mailer/emails:/app/packages/mailer/emails
      - ./packages/mailer/src:/app/packages/mailer/src
    networks:
      - db-lab
    ports:
      - 3003:3003
networks:
  db-lab:
    name: db-lab-network

volumes:
  mailer-volume:
